In [2]:
my_list=[1,2,3,4,5]
print("Python List Multiplied by 2:", my_list*2)
import numpy as np
my_array= np.array(my_list)
print("Numpy Array Multiplied by 2:",my_array*2)

Python List Multiplied by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array Multiplied by 2: [ 2  4  6  8 10]


In [34]:
import numpy as np

line_array= np.array([10,20,30])
print("1D Array Shape:", line_array.shape)
l_arr=np.zeros((2,3))
print(l_arr)
matrix=np.array([[1,2,3],[4,5,6]])
print("\n2D Matrix:")
print(matrix)
print("2D Matrix Shape:",matrix.shape)

zeros_grid=np.zeros((3,3))
print("\n3x3 Grid of Zeros:")
print(zeros_grid)

random_grid=np.random.rand(2,2)
print("\n2x2 Grid of Random Numbers:")
print(random_grid)

my_grid=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(my_grid)
print(my_grid.shape)

m_grid=np.array([[1],[2],[3],[4]])
print(m_grid)
print(m_grid.shape)


robarto_karlos=np.random.rand(2,3)
r_k=np.zeros((2,3))
print(r_k)
for i in range(len(r_k)):
    for j in range(len(r_k)+1):
        r_k[i][j]=np.random.rand()
print(robarto_karlos)
print(r_k)

mp_grid=np.array([[[1],[2],[3]],
                  [[4],[5],[6]],
                  [[7],[8],[9]]
                 ])
print(mp_grid)

n_o_r=len(mp_grid)
n_o_c=len(mp_grid[0])
print(n_o_r,n_o_c)


print(mp_grid)
print(mp_grid.shape)

print(mp_grid[0])
print(mp_grid[0].shape)

print(mp_grid[0][0])
print(mp_grid[0][0].shape)

1D Array Shape: (3,)
[[0. 0. 0.]
 [0. 0. 0.]]

2D Matrix:
[[1 2 3]
 [4 5 6]]
2D Matrix Shape: (2, 3)

3x3 Grid of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2x2 Grid of Random Numbers:
[[0.73490472 0.6251185 ]
 [0.63098217 0.1026769 ]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.88975304 0.69647762 0.52235315]
 [0.93617711 0.37031119 0.36407925]]
[[0.73523831 0.49116273 0.20176495]
 [0.20339377 0.16966969 0.40809062]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
3 3
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
[[1]
 [2]
 [3]]
(3, 1)
[1]
(1,)
